import './globals.css';

import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body
        className={
          poppins.className +
          ' flex min-h-screen flex-col items-center p-24 bg-dots bg-[#313434] text-white'
        }
      >
        <h1 className='text-6xl font-bold mb-96'>Short - It</h1>
        {children}
      </body>
    </html>
  );
}
